//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanReosurces.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerGrowth
    {
        public long Id_growth { get; set; }
        public long Id_employee { get; set; }
        public System.DateTime Promotion_date { get; set; }
        public string New_position { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}